# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'pal' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for pal

  target 'pal-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'palTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'pal-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for pal-tvOS

  target 'pal-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
